spring:
  application:
    name: lms-email-impl
  profiles:
    active: redis
  session:
    store-type: none
lmsemail:
  enabled: false
  defaultFrom: essnorep@iu.edu
---

spring:
  profiles: redis
  session:
    store-type: redis

---

spring:
  profiles: email
  mail:
    host: mail-relay.iu.edu
    port: 465
    username: lmssmtp
    password: ${spring.mail.password}
    properties:
      mail:
        smpt:
          auth: true
          #          starttls:
          #            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
lmsemail:
  enabled: true